p = input('Digite alguma coisa:')
print('o tipo primitivo dessa string é: ')
print(type(p))
print('Só tem espaços?')
print(p.isspace())
print('É um número?')
print(p.isnumeric())
print('É alfabético?')
print(p.isalpha())
print('É alfanumérico?')
print(p.isalnum())
print('Está em letra maiúscula?')
print(p.isupper())
print('Está em minúscula?')
print(p.islower())
print('Está capitalizada?')
print(p.istitle())
###########################################
p = input('Digite alguma coisa:')
print('O tipo primitivo dessa string é', type(p))
print('Se tem espaços?', p.isspace())
print('É um número?', p.isnumeric())
print('É alfabético?', p.isalpha())
print('É alfanumérico?', p.isalnum())
print('Está em letra maiúscula?', p.isupper())
print('Está em letra minúscula?', p.islower())
print('Está capitalizada?', p.istitle())